package com.covoiturage.mailer;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class Mailer {

    private static Mailer instance;
    private static Properties mailServerProperties;
    private static Session getMailSession;
    private static MimeMessage generateMailMessage;

    private static String senderEmail;
    /**
     * this password is an app password generated by gmail not the gmail account passowrd
    * */
    private static String senderEmailPassword;

    private Mailer() {
        // Setup Mail Server Properties..
        mailServerProperties = System.getProperties();
        mailServerProperties.put("mail.smtp.port", "587");
        mailServerProperties.put("mail.smtp.auth", "true");
        mailServerProperties.put("mail.smtp.starttls.enable", "true");
        // Mail Server Properties have been setup successfully

        // get Mail Session..
        getMailSession = Session.getDefaultInstance(mailServerProperties, null);
    }

    private static void loadSenderEmailProp() {
        try (InputStream input = Thread.currentThread().
                getContextClassLoader().
                getResourceAsStream( "mailer.properties" )) {

            Properties properties = new Properties();

            if (input == null) {
                System.out.println("Sorry, unable to find mailer.properties");
                return;
            }

            //load a properties file from class path, inside static method
            properties.load(input);

            senderEmail = properties.getProperty("sender.email");
            senderEmailPassword = properties.getProperty("sender.password");

        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public static void sendEmail(ArrayList<String> emails, String subject, String body) throws MessagingException {

        if(instance == null) {
            instance = new Mailer();
        }

        generateMailMessage = new MimeMessage(getMailSession);

        for (int i = 0; i < emails.size(); i++)
        {
            generateMailMessage.addRecipient(Message.RecipientType.TO, new InternetAddress(emails.get(i)));
        }
        // Subject
        generateMailMessage.setSubject(subject);

        //Email Body in html
        generateMailMessage.setContent(body, "text/html");
        // Mail Session has been created successfully

        // Get Session and Send mail
        Transport transport = getMailSession.getTransport("smtp");


        //getting email Sender properties from mailer.properties
        Mailer.loadSenderEmailProp();

        transport.connect("smtp.gmail.com", senderEmail, senderEmailPassword);
        transport.sendMessage(generateMailMessage, generateMailMessage.getAllRecipients());
        transport.close();

    }


    public static void main(String args[]) throws MessagingException {
        ArrayList<String> emails = new ArrayList<String>();
        emails.add("abd.bfscpge@gmail.com");
        String subject = "Greetings from Crunchify..";
        String body = "Testaaaaa email by Crunchify.com JavaMail API example. \" + \"<br><br> Regards, <br>Crunchify Admin";
        Mailer.sendEmail(emails, subject, body);
        Mailer.sendEmail(emails, subject, body);
        Mailer.sendEmail(emails, subject, body);
        System.out.println("\n\n ===> Your Java Program has just sent an Email successfully. Check your email..");
    }

}